apiVersion: v1
kind: Service
metadata:
        name: apigateway
        labels:
                app: apigateway
spec:
        type: ClusterIP
        selector:
                app: apigateway
        ports:
        - name: apigatewayport
          protocol: TCP
          port: 8080
          targetPort: 8080
