apiVersion: apps/v1
kind: Deployment
metadata:
        name: cursusdb
spec:
        selector:
                matchLabels:
                        app: cursusdb
        replicas: 1
        template:
                metadata:
                        labels:
                                app: cursusdb
                                chaos: immune
                spec:
                        containers:
                        - name: cursusdb
                          image: mongo
