apiVersion: v1
kind: Service
metadata:
        name: financialdb
        labels:
                app: financialdb
spec:
        type: ClusterIP
        selector:
                app: financialdb
        ports:
        - name: financialdb
          protocol: TCP
          port: 3306
          targetPort: 3306
