apiVersion: v1
kind: Service
metadata:
        name: kafkabroker
        labels:
                app: kafkabroker
spec:
        type: ClusterIP
        selector:
                app: kafka
        ports:
        - name: kport
          protocol: TCP
          port: 9092
          targetPort: 9092
