apiVersion: v1
kind: Service
metadata:
        name: onderzoekservice
        labels:
                app: onderzoekservice
spec:
        type: ClusterIP
        selector:
                app: onderzoekservice
        ports:
        - name: onderzoekservice
          protocol: TCP
          port: 2227
          targetPort: 2227

