apiVersion: v1
kind: Service
metadata:
        name: onderzoekdb
        labels:
                app: onderzoekdb
spec:
        type: ClusterIP
        selector:
                app: onderzoekdb
        ports:
        - name: onderzoekdb
          protocol: TCP
          port: 3306
          targetPort: 3306
