apiVersion: v1
kind: Service
metadata:
        name: professordb
        labels:
                app: professordb
spec:
        type: ClusterIP
        selector:
                app: professordb
        ports:
        - name: professordb
          protocol: TCP
          port: 3306
          targetPort: 3306

