apiVersion: v1
kind: Service
metadata:
        name: studentservice
        labels:
                app: studentservice
spec:
        type: ClusterIP
        selector:
                app: studentservice
        ports:
        - name: studentservice
          protocol: TCP
          port: 2222
          targetPort: 2222
