apiVersion: v1
kind: Service
metadata:
        name: studentdb
        labels:
                app: studentdb
spec:
        type: ClusterIP
        selector:
                app: studentdb
        ports:
        - name: studentdb
          protocol: TCP
          port: 3306
          targetPort: 3306
